services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: jhu
      POSTGRES_PASSWORD: jhu123
      POSTGRES_DB: jhu
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  sportsapp:
    build: .
    image: sportsapp:latest
    environment:
      HOST: 0.0.0.0
      PORT: 8000
    ports:
      - "8000:8000"

volumes:
  pgdata:

